-- Restaurant SaaS Schema with RLS Tenant Isolation
-- Generated by Traycer for foodtruck-ops-v2

-- =============================================
-- TENANCY & RLS ISOLATION
-- =============================================

-- Ensure business_id GUC exists (set only inside tenant blocks)
CREATE TABLE IF NOT EXISTS app_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT UNIQUE,        -- 'app.business_id' or 'app.db_name'
  value JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default business_id GUC for tenant isolation
INSERT INTO app_settings (key, value) VALUES ('app.business_id', '{"value": "uuid-bus-123"}');

-- =============================================
-- TENANT ISOLATION POLICIES
-- =============================================

-- Core POS tables: Tenant-only via RLS policies on business_id GUC (NOT AR scopes)

-- Orders table
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_code TEXT NOT NULL UNIQUE,      -- e.g., 'POS-20261025-001'
  business_id UUID NOT NULL,           -- RLS policy
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orders RLS Policy: Tenant isolation via business_id GUC (NOT AR scoped)
CREATE POLICY tenant_isolation ON orders
  USING (
    business_id = current_setting('app.business_id')::uuid
  )
  WITH CHECK (
    business_id = current_setting('app.business_id')::uuid
  );

-- Orders Index for RLS enforcement and performance
CREATE INDEX idx_orders_business_id ON orders (business_id);

-- KitchenOrders table
DROP TABLE IF EXISTS kitchen_orders;
CREATE TABLE kitchen_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending', -- pending, cooking, ready_for_pickup, ready, sold_out
  prepared_at TIMESTAMPTZ,
  kitchen_order_code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- KitchenOrders RLS Policy: Tenant isolation via business_id GUC (NOT AR scoped)
CREATE POLICY tenant_isolation ON kitchen_orders
  USING (
    order_id = current_setting('app.business_id')::uuid
  )
  WITH CHECK (
    order_id = current_setting('app.business_id')::uuid
  );

-- KitchenOrders Index
CREATE INDEX idx_kitchen_orders_order_id ON kitchen_orders (order_id);

-- PaymentHistory table
DROP TABLE IF EXISTS payment_history;
CREATE TABLE payment_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  amount NUMERIC(10,2),
  currency TEXT NOT NULL DEFAULT 'USD',
  transaction_code TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'completed', -- completed, failed, refunded
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- PaymentHistory RLS Policy: Tenant isolation via business_id GUC (NOT AR scoped)
CREATE POLICY tenant_isolation ON payment_history
  USING (
    order_id = current_setting('app.business_id')::uuid
  )
  WITH CHECK (
    order_id = current_setting('app.business_id')::uuid
  );

-- CashRegister table (POS-specific)
DROP TABLE IF EXISTS cash_register;
CREATE TABLE cash_register (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_code TEXT UNIQUE NOT NULL,
  amount NUMERIC(10,2),
  currency TEXT NOT NULL DEFAULT 'USD',
  payment_method TEXT NOT NULL DEFAULT 'cash', -- cash, credit_card, debit_card
  status TEXT NOT NULL DEFAULT 'completed', -- completed, refunded
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CashRegister RLS Policy: Tenant isolation via business_id GUC (NOT AR scoped)
CREATE POLICY tenant_isolation ON cash_register
  USING (
    id = current_setting('app.business_id')::uuid
  )
  WITH CHECK (
    id = current_setting('app.business_id')::uuid
  );

-- DailyReport table
DROP TABLE IF EXISTS daily_report;
CREATE TABLE daily_report (
  report_code TEXT NOT NULL UNIQUE,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  total_sales NUMERIC(10,2),
  total_kitchen_orders NUMERIC(10,2),
  total_payments NUMERIC(10,2),
  status TEXT NOT NULL DEFAULT 'generated', -- generated, processed
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DailyReport RLS Policy: Tenant isolation via business_id GUC (NOT AR scoped)
CREATE POLICY tenant_isolation ON daily_report
  USING (
    report_code = current_setting('app.business_id')::uuid
  )
  WITH CHECK (
    report_code = current_setting('app.business_id')::uuid
  );

-- =============================================
-- SYNC & RECONCILIATION LAYER (POS → Kitchen → Payment)
-- =============================================

-- Sync table for POS-to-Kitchen state transfer
DROP TABLE IF EXISTS sync_queue;
CREATE TABLE sync_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending', -- pending, synced_to_kitchen, completed
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SyncQueue RLS Policy: Tenant isolation via business_id GUC (NOT AR scoped)
CREATE POLICY tenant_isolation ON sync_queue
  USING (
    order_id = current_setting('app.business_id')::uuid
  )
  WITH CHECK (
    order_id = current_setting('app.business_id')::uuid
  );

-- =============================================
-- INDEXES FOR RLS PERFORMANCE
-- =============================================

CREATE INDEX idx_orders_business ON orders (business_id);
CREATE INDEX idx_kitchen_orders_order ON kitchen_orders (order_id, status);
CREATE INDEX idx_payment_history_order ON payment_history (order_id);
CREATE INDEX idx_sync_queue_order ON sync_queue (order_id);

-- =============================================
-- DATA SEEDING: Demo Data for POS/POS-20261025-001
-- =============================================

-- Seed sample data if tables exist but are empty
INSERT INTO orders (id, order_code, business_id) VALUES
  (gen_random_uuid(), 'POS-20261025-001', uuid_bus_123),
  (gen_random_uuid(), 'POS-20261025-002', uuid_bus_124);

INSERT INTO kitchen_orders (id, order_id, status, kitchen_order_code) VALUES
  ((SELECT id FROM orders WHERE order_code='POS-20261025-001'), 'kitchen-001', 'cooking', 'KOH-20261025-001'),
  ((SELECT id FROM orders WHERE order_code='POS-20261025-002'), 'kitchen-002', 'ready_for_pickup', 'KOH-20261025-002');

INSERT INTO payment_history (id, order_id, amount, currency, status) VALUES
  ((SELECT id FROM orders WHERE order_code='POS-20261025-001'), 'pmt-001', 12.99, 'USD', 'completed'),
  ((SELECT id FROM orders WHERE order_code='POS-20261025-002'), 'pmt-002', 8.50, 'USD', 'completed');

INSERT INTO cash_register (id, transaction_code, amount, currency, payment_method, status) VALUES
  ((SELECT id FROM orders WHERE order_code='POS-20261025-001'), 'cash-reg-001', 12.99, 'USD', 'cash', 'completed');

INSERT INTO daily_report (report_code, generated_at, total_sales, total_kitchen_orders, status) VALUES
  ('DAILY-20261025-001', NOW(), 25.49, 3, 'generated');
